# fly.toml app configuration file generated for kickoff-sync on 2025-07-01T09:46:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kickoff-sync"
primary_region = "fra"

[build]

[[vm]]
  size = "shared-cpu-1x"

[processes]
cron = "supercronic /app/crontab"
